###################################################################
# Spring Boot application configs specific to development profile #
###################################################################

#### PostgreSQL database configuration ####
spring.datasource.url=jdbc:postgresql://${POSTGRES_DOCKER_HOST:localhost}:${POSTGRES_DOCKER_PORT:5433}/${POSTGRES_DB:unibook_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

#### JPA/Hibernate configuration ####
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create

# Server configuration
server.port=${BACKEND_PORT:8080}

# Frontend configuration
frontend.url=${FRONTEND_URL:http://localhost}
frontend.port=${FRONTEND_PORT:5173}

#### Docker configuration ####
# Disable Docker Compose integration
spring.docker.compose.enabled=false 
# Start container when Spring Boot application starts
# spring.docker.compose.file=../compose.yaml 
