###################################################################
# Spring Boot application configs specific to development profile #
###################################################################

#### PostgreSQL database configuration ####
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:payment_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

#### JPA/Hibernate configuration ####
spring.jpa.hibernate.ddl-auto=update

# Server configuration
server.port=${BACKEND_PORT:8080}

#### Docker configuration ####
# Disable Docker Compose integration
spring.docker.compose.enabled=false 
# Start container when Spring Boot application starts
# spring.docker.compose.file=../compose.yaml 
